config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  DinnerDash::Application.routes.draw do
   mount Resque::Server.new, at: "/resque"
  end

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  resources :charges
  resources :items
  root 'home#index'
  resources :items
	resources :orders
  resources :categories
  resources :addresses

  resources :mailing_addresses, controller: 'addresses', type: 'MailingAddress'
  resources :billing_addresses, controller: 'addresses', type: 'BillingAddress'

  resources :users
  resources :home

  namespace :admin do
    resources :items, :categories, :orders, :order_items
    resources :stores, except: :patch
    patch 'stores/:id', to: 'stores#authorize_store', as: "authorize_store"
    get 'dashboard', to: 'dashboard#show'
  end

  get 'cart',        to: 'carts#show',  as: 'cart'

  get 'confirmation', to: 'confirmations#show'

  get 'code', to: 'home#code'

  get 'complete_delivery_order', to: 'orders#create'

  get 'checkout',         to: 'checkouts#show'
  get 'complete_order',   to: 'checkouts#complete_order'

  post 'add_item',         to: 'carts#add_item',       as: 'add_item'
  get 'remove_item',      to: 'carts#remove_item',    as: 'remove_item'
  put 'update_quantity',  to: 'carts#update_quantity',as: 'update_quantity'

  namespace :seller do
    resources :items, :orders
    get  'stores',                    to: 'seller#index',           as: 'dashboard'
    get  'store/:id/edit',            to: 'seller#edit',            as: 'store_edit'
    get  'store/:id',                 to: 'seller#show',            as: 'store_show'
    patch 'store/:id',                to: 'seller#update',          as: 'store_update'
    patch 'store/add_manager/:id',    to: 'seller#add_manager',     as: 'store_add_manager'
    patch 'store/remove_manager/:id', to: 'seller#remove_manager',  as: 'store_remove_manager'
  end

  get 'stores', to: 'store_dashboard#index', as: 'store_dashboard'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get  'request_store', to: 'stores#new', as: 'request_store'
  post 'send_store_request',  to: 'stores#create'

  get 'about',      to: 'about#show'

  get "contact_us", to: 'contact_us#new'
  resources "contact_us", only: [:create]

  get ':store_name', to: 'stores#show', as: 'stores'
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :status, inclusion: {in: %w(paid completed canceled ordered)}
  validates :store_id, presence: true
  has_many :order_items
  has_many :items, through: :order_items
  belongs_to :user
  belongs_to :address
  belongs_to :shipping_address
  belongs_to :billing_address
  belongs_to :store

  scope :paid,      -> { where(status: "paid") }
  scope :completed, -> { where(status: "completed") }
  scope :canceled,  -> { where(status: 'canceled') }
  scope :ordered,   -> { where(status: 'ordered')}

  def self.valid_statuses
    ['paid', 'completed', 'canceled', 'ordered']
  end

  def subtotal
    line_totals = order_items.map {|order_item| order_item.line_total}
    line_totals.reduce(:+)
  end

  def tax
    subtotal * ".05".to_f
  end

  def total
    subtotal + tax
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @paid_orders = Order.where(:status => "paid")
    @completed_orders = Order.where(:status => "completed")
    @canceled_orders = Order.where(:status => "canceled")
    @ordered = Order.where(:status => "ordered")
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_orders_path, notice: "Order Successfully Updated"
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user
  before_action :set_order, only: [:show]

  def create
    if cart.items.empty?
      redirect_to confirmation_path
    else
      create_order(params)
      charge_stripe(params)
      redirect_to charges_path
    end
  end

  def index
    @orders = current_user.orders
  end

  def new

    @shipping_addresses = current_user.shipping_addresses
    @billing_addresses = current_user.billing_addresses
    if cart.empty?
      redirect_to cart_path, notice: 'Please add items to your cart before checking out. Thank you!'
    elsif @shipping_addresses.empty?
      @amount = Cart.total(session)
      session[:return_to] = new_order_path
      flash[:message] = 'Please Enter a Shipping Address'
      redirect_to new_address_path(category: "shipping")
    elsif @billing_addresses.empty?
      @amount = Cart.total(session)
      session[:return_to] = new_order_path
      flash[:message] = 'Please Enter a Billing Address'
      redirect_to new_address_path(category: "billing")
    else
      @amount = Cart.total(session)
    end
  end

  private

  def items_by_store_id
    cart.items.group_by{|item| Item.find(item[0].to_i).store_id}
  end

  def create_order(params)
    order_creator = OrderCreator.new(items_by_store_id, session[:user_id], params[:order]["shipping_address_id"], params[:order]["billing_address_id"])
    orders = order_creator.process_orders

    totals = orders.map {|order| order.total}
    order_total = totals.reduce(:+)

    order_ids = orders.map {|order| order.id}

    Resque.enqueue(UserConfirmationJob, current_user.id, order_ids)

    session[:cart_items] = {}
    session[:order_total] = order_total
  end

  def charge_stripe(params)
    @amount = (session[:order_total].to_f*100).to_i
      @total_paid = session[:order_total]
      customer = Stripe::Customer.create(
        :email => 'example@stripe.com',
        :card  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
  end

  def authenticate_user
    unless current_user
      flash[:notice] = 'Please log in or create account to complete order'
      session[:return_to] = cart_path
      redirect_to new_user_path
    end
  end

  def set_order
    if current_user.orders.collect { |order| order.id }.include?(params[:id].to_i)
      @order = current_user.orders.find(params[:id])
    else
      redirect_to :root
    end
  end
end

app/controllers/seller/orders_controller.rb
class Seller::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to seller_store_edit_path(@order.store.id), notice: "Order Successfully Updated"
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/views/admin/orders/index.html.erb
<div class="container">
  <h1>Orders</h1>

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#paid_orders" role="tab" data-toggle="tab">Paid Orders</a></li>
    <li role="presentation"><a href="#completed_orders" role="tab" data-toggle="tab">Completed Orders</a></li>
    <li role="presentation"><a href="#canceled_orders" role="tab" data-toggle="tab">Canceled Orders</a></li>
    <li role="presentation"><a href="#ordered" role="tab" data-toggle="tab">Pending</a></li>
  </ul>
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="paid_orders">
      <h3 class="page-header">Paid Orders (<%= "#{@paid_orders.count}" %>)</h3>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Order For</th>
            <th>Status</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <% @paid_orders.each do |order| %>
            <tr>
              <td><%= link_to "#{ order.user.full_name }",admin_order_path(order.id) %></td>
              <td><%= link_to "#{ order.status }", admin_order_path(order.id) %></td>
              <td class="order-buttons">
                <%  if order.status == 'ordered' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch, class: "btn btn-sm btn-danger" %>
                  <%= button_to "Mark As Paid", admin_order_path(order, order: { status: 'paid' }), method: :patch %>
                <%  elsif order.status == 'paid' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch, class: "btn btn-sm btn-danger" %>
                  <%= button_to "Mark As Completed", admin_order_path(order, order: { status: 'completed' }), method: :patch, class: "btn btn-sm btn-primary" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane fade active" id="completed_orders">
      <h3 class="page-header">Completed Orders(<%="#{@completed_orders.count}"%>)</h3>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Order For</th>
            <th>Status</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <% @completed_orders.each do |order| %>
            <tr>
              <td><%= link_to "#{ order.user.full_name }",admin_order_path(order.id) %></td>
              <td><%= link_to "#{ order.status }", admin_order_path(order.id) %></td>
              <td class="order-buttons">
                <%  if order.status == 'ordered' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch %>
                  <%= button_to "Mark As Paid", admin_order_path(order, order: { status: 'paid' }), method: :patch %>
                <%  elsif order.status == 'paid' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch %>
                  <%= button_to "Mark As Completed", admin_order_path(order, order: { status: 'completed' }), method: :patch %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="canceled_orders">
      <h3 class="page-header">Canceled Orders(<%="#{@canceled_orders.count}"%>)</h3>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Order For</th>
            <th>Status</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <% @canceled_orders.each do |order| %>
            <tr>
              <td><%= link_to "#{ order.user.full_name }",admin_order_path(order.id) %></td>
              <td><%= link_to "#{ order.status }", admin_order_path(order.id) %></td>
              <td class="order-buttons">
                <%  if order.status == 'ordered' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch %>
                  <%= button_to "Mark As Paid", admin_order_path(order, order: { status: 'paid' }), method: :patch %>
                <%  elsif order.status == 'paid' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch %>
                  <%= button_to "Mark As Completed", admin_order_path(order, order: { status: 'completed' }), method: :patch %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="ordered">
      <h3 class="page-header">Pending Orders(<%="#{@completed_orders.count}"%>)</h3>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Order For</th>
            <th>Status</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <% @ordered.each do |order| %>
            <tr>
              <td><%= link_to "#{ order.user.full_name }",admin_order_path(order.id) %></td>
              <td><%= link_to "#{ order.status }", admin_order_path(order.id) %></td>
              <td class="order-buttons">
                <%  if order.status == 'ordered' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch, class: "btn btn-sm btn-danger" %>
                  <%= button_to "Mark As Paid", admin_order_path(order, order: { status: 'paid' }), method: :patch, class: "btn-sm btn-primary" %>
                <%  elsif order.status == 'paid' %>
                  <%= button_to "Cancel", admin_order_path(order, order: { status: 'canceled' }), method: :patch %>
                  <%= button_to "Mark As Completed", admin_order_path(order, order: { status: 'completed' }), method: :patch %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<table class='tg'>
  <tr>
    <th>
      Purchasers Email:
    </th>
    <th>
      Purchasers Name:
    </th>
    <th>
      Ordered At:
    </th>
    <th>
      Roughly Ordered At:
    </th>
  </tr>
  <tr>
    <td>
      <%= @order.user.email_address %>
    </td>
    <td>
      <%= @order.user.full_name %>
    </td>
    <td>
      <%= @order.created_at.strftime("%d %b. %Y")%>, <%= @order.created_at.strftime("%l:%M %p") %>
    </td>
    <td>
      <%= time_ago_in_words(@order.created_at) %> ago.
    </td>
  </tr>
</table><br>

<table class='tg'
  <tr>
    <th>
      Order status:
    </th>
    <th>
      Items Ordered:
    </th>
    <th>
      Item Price:
    </th>
    <th>
      Delete Option:
    </th>
    <th>
      Update Quantity:
    </th>
    <th>
      Quantity:
    </th>
  </tr>
  <tr>
    <td><%= @order.status %></td>
    <% @order.order_items.each do |order_item| %></td>
      <td><%= link_to order_item.item.name, item_path(order_item.item.id) %></td>
        <td><%= number_to_currency(order_item.item.price) %></td>

        <% if @order.status == 'ordered' || @order.status == 'paid' %>
          <td><%= button_to 'Delete', admin_order_item_path(order_item.id), :method => :delete %></td>
          <%= form_tag admin_order_item_path(order_item.id), :method => :put do  %>
          <%= hidden_field_tag "order_item[item_id]", order_item.id %>
          <td><%= number_field_tag "order_item[quantity]", order_item.quantity, :min => 1, :max => 100 %>
          <%= submit_tag "update" %>
          <% end %>
        <% end %></td>
      <td><%= order_item.quantity %></td>
  </tr>
</table><br>
<table class='tg'>
  <tr>
    <th>
      Subtotal:
    </th>
    <th>
      Total Price:
    </th>
    <th>
      Options:
    </th>
  </tr>
  <tr>
    <% end %>
    <td><%= number_to_currency(@order.subtotal)%></td>
    <td><%= number_to_currency(@order.total)%></td>
    <td class="order-buttons">
      <%  if @order.status == 'ordered' %>
        <%= button_to "Cancel", admin_order_path(@order, order: { status: 'canceled' }), method: :patch %>
        <%= button_to "Mark As Paid", admin_order_path(@order, order: { status: 'paid' }), method: :patch %>
      <%  elsif @order.status == 'paid' %>
        <%= button_to "Cancel", admin_order_path(@order, order: { status: 'canceled' }), method: :patch %>
        <%= button_to "Mark As Completed", admin_order_path(@order, order: { status: 'completed' }), method: :patch %>
      <% end %><br>
    </td>
  </tr>
</table>