config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  DinnerDash::Application.routes.draw do
   mount Resque::Server.new, at: "/resque"
  end

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  resources :charges
  resources :items
  root 'home#index'
  resources :items
	resources :orders
  resources :categories
  resources :addresses

  resources :mailing_addresses, controller: 'addresses', type: 'MailingAddress'
  resources :billing_addresses, controller: 'addresses', type: 'BillingAddress'

  resources :users
  resources :home

  namespace :admin do
    resources :items, :categories, :orders, :order_items
    resources :stores, except: :patch
    patch 'stores/:id', to: 'stores#authorize_store', as: "authorize_store"
    get 'dashboard', to: 'dashboard#show'
  end

  get 'cart',        to: 'carts#show',  as: 'cart'

  get 'confirmation', to: 'confirmations#show'

  get 'code', to: 'home#code'

  get 'complete_delivery_order', to: 'orders#create'

  get 'checkout',         to: 'checkouts#show'
  get 'complete_order',   to: 'checkouts#complete_order'

  post 'add_item',         to: 'carts#add_item',       as: 'add_item'
  get 'remove_item',      to: 'carts#remove_item',    as: 'remove_item'
  put 'update_quantity',  to: 'carts#update_quantity',as: 'update_quantity'

  namespace :seller do
    resources :items, :orders
    get  'stores',                    to: 'seller#index',           as: 'dashboard'
    get  'store/:id/edit',            to: 'seller#edit',            as: 'store_edit'
    get  'store/:id',                 to: 'seller#show',            as: 'store_show'
    patch 'store/:id',                to: 'seller#update',          as: 'store_update'
    patch 'store/add_manager/:id',    to: 'seller#add_manager',     as: 'store_add_manager'
    patch 'store/remove_manager/:id', to: 'seller#remove_manager',  as: 'store_remove_manager'
  end

  get 'stores', to: 'store_dashboard#index', as: 'store_dashboard'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get  'request_store', to: 'stores#new', as: 'request_store'
  post 'send_store_request',  to: 'stores#create'

  get 'about',      to: 'about#show'

  get "contact_us", to: 'contact_us#new'
  resources "contact_us", only: [:create]

  get ':store_name', to: 'stores#show', as: 'stores'
end

app/models/store.rb
class Store < ActiveRecord::Base
  scope :authorized, -> { where(authorized: true)}
  scope :online, -> { where(online: true)}

  before_validation :remove_slug_spaces

  validates :name, :slug, :user_id, uniqueness: true
  validates :description, :slug, :name, presence: true
  has_many :items
  has_many :orders
  belongs_to :user
  has_many :store_managers
  has_many :users, through: :store_managers

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def remove_slug_spaces
    self.slug.gsub!(/[" "]/, '_')
  end

  def completed_orders
    orders.where(:status => "completed")
  end

  def paid_orders
    orders.where(:status => "paid")
  end

  def canceled_orders
    orders.where(:status => "canceled")
  end

  def recent_orders
    orders.where(:status => "ordered")
  end

  def self.waitng_approval
    where(:authorized == false)
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::BaseController

  def index
    @authorized_stores = Store.where(:authorized => true, :online => true)
    @offline_stores = Store.where(:online => false)
    @stores_waiting_approval = Store.where(:authorized => false)
  end

  def edit
    @store = Store.find(params[:id])
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.create(store_params)
    if @store.save
      flash[:notice] = "Thanks for your store request, check your inbox for a response."
      redirect_to root_path
    else
      flash[:notice] = "Unable to process your request."
      render :new
    end
  end

  def update
    @store = Store.find(params[:id])
    @store.update(store_params)
    redirect_to admin_stores_path
  end

  def authorize_store
    @store = Store.find(params[:id])
    if @store.update(store_params)
      Resque.enqueue(StoreConfirmationJob, @store.user.id)
    end
    redirect_to admin_stores_path
  end

  def destroy
    Store.find(params[:id]).destroy
    redirect_to admin_stores_path
  end
  def store_params
    params.require(:store).permit(:name, :description, :image, :slug, :request_message, :user_id, :authorized, :online)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def show
    @store = Store.authorized.online.where(slug: params[:store_name]).first
    if @store
      render :show
    else
      redirect_to '/404'
    end
  end

  def create
    @store = Store.create(store_params)
    current_user.update(:role => "seller")
    if @store.save
      flash[:notice] = "Thanks for your store request, check your inbox for a response."
      redirect_to root_path
    else
      flash[:notice] = "Unable to process your request."
      render :new
    end
  end

  def new
    @store = Store.new
  end

  private
  def store_params
    params.require(:store).permit(:name, :description, :image, :slug, :request_message, :user_id)
  end
end

app/views/admin/stores/edit.html.erb
<%= render "layouts/errors", object: @store %>

<div class="container">

      <h4 class="page-header">Edit Users Store</h4>
        <%= bootstrap_form_for @store, :url => {:action => :update} do |f| %>
        <%= f.text_field :name %>
        <%= f.text_area  :description %>
        <%= f.text_field :slug, placeholder: "example: louies_ck_for_men" %>
        <%= f.file_field :image %>
        <%= f.text_area  :request_message, placeholder: "Why do you want to sell on dope threads?" %>
        <%= f.hidden_field :user_id, value: @store.user_id %>

        <%= f.submit class: "btn btn-success" %>
      <% end %>
    </div>

app/views/admin/stores/index.html.erb
<div class="container">
  <h2>Store Admin</h2>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#active_stores"
      role="tab" data-toggle="tab">Active Stores</a></li>
    <li role="presentation"><a href="#inactive_stores" role="tab" data-toggle="tab">Offline Stores</a></li>
    <li role="presentation"><a href="#pending_approval" role="tab" data-toggle="tab">Stores Pending Approval</a></li>
  </ul>

  <div class="container">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="active_stores">
        <h4 class="page-header">Active Stores (<%= "#{@authorized_stores.count}" %>)</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Slug</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody id="admin_categories_edit_table">
            <% @authorized_stores.each do |store| %>
              <tr>
                <td><span class="item_title"><%= link_to store.name, admin_store_path(store) %><span></td>
                <td><%= store.description %></td>
                <td><%= store.slug %></td>
                <% if store.online %>
                <td><%= link_to 'Take Offline', admin_store_path(store, store:{online:'false'}), method: 'patch', class: 'btn btn-danger', id: "#{store.slug}", data: {confirm: 'Are you sure you want to take this store offline?'}%></td>
                <% else %>
                <td><%= link_to 'Bring Back Online', admin_store_path(store, store:{online:'true'}), method: 'patch', class: 'btn btn-success', id: "#{store.slug}",  data: {confirm: 'Are you sure you want to bring this store online?'}%></td>
                <% end  %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div role="tabpanel" class="tab-pane fade in" id="inactive_stores">
        <h4 class="page-header">Offline Stores (<%= "#{@offline_stores.count}" %>)</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Slug</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody id="admin_categories_edit_table">
            <% @offline_stores.each do |store| %>
              <tr>
                <td><span class="item_title"><%= link_to store.name, admin_store_path(store) %><span></td>
                <td><%= store.description %></td>
                <td><%= store.slug %></td>
                <% if store.online %>
                <td><%= link_to 'Take Offline', admin_store_path(store, store:{online:'false'}), method: 'patch', class: 'btn', id: "#{store.slug}", data: {confirm: 'Are you sure you want to take this store offline?'}%></td>
                <% else %>
                <td><%= link_to 'Bring  Back Online', admin_store_path(store, store:{online:'true'}), method: 'patch', class: 'btn btn-success',  id: "#{store.slug}", data: {confirm: 'Are you sure you want to bring this store online?'}%></td>
                <% end  %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div role="tabpanel" class="tab-pane fade in" id="pending_approval">
        <h4 class="page-header">Stores Pending Approval (<%= "#{@stores_waiting_approval.count}" %>)</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Slug</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @stores_waiting_approval.each do |store| %>
              <tr>
                <td><span class="item_title"><%= link_to store.name, admin_store_path(store) %><span></td>
                <td><%= store.description %></td>
                <td><%= store.slug %></td>
                <td><%= link_to 'Approve Request', admin_authorize_store_path(store.id, store:{authorized:'true'}), method: 'patch', class: 'btn btn-success',id: "#{store.slug}_approve", data: {confirm: 'Are you sure you want to approve the creation of this store?'}%></td>
                <td><%= link_to 'Delete Request', admin_store_path(store), class: "btn btn-danger", id: "#{store.slug}_delete", method: :delete, data: { confirm: 'Are you want to delete this store request?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/stores/show.html.erb
  <div class="store-header">
    <div class="store-header-image">
      <%= image_tag @store.image.url(:medium) %>

    </div>
    <div class="store-name">
      <h2 id="store-name"> <%= @store.name.titleize %> </h2>

    </div>
  </div>
  <div class="store-description">
    <%= @store.description %>
    <div class="text-right">
      <%= link_to("Edit Store Details", edit_admin_store_path(@store), class: "btn btn-sm btn-success") %>
      <%= link_to("Create a New Item", {:controller => "admin/items", :action => "new", :store_id => @store.id}, class: "btn btn-sm btn-primary") %>
    </div>
  </div>
  <div class="store-items-container">
    <div id="masonry-grid">
      <div class="grid-sizer">
        <% @store.items.each do |item| %>
        <div class="grid-item">
          <%= link_to item.name, item_path(item) %>
          <%= link_to (image_tag item.image.url(:medium)), item_path(item) %><br/>
          <%= item.description %>
          <li><%= link_to("Delete Item", admin_item_path(item) , method: :delete) %></li>
          <li><%= link_to("Edit Item", edit_admin_item_path(item)) %></li>

        </div>
        <% end %>
      </div>
    </div>
  </div>