config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  DinnerDash::Application.routes.draw do
   mount Resque::Server.new, at: "/resque"
  end

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  resources :charges
  resources :items
  root 'home#index'
  resources :items
	resources :orders
  resources :categories
  resources :addresses

  resources :mailing_addresses, controller: 'addresses', type: 'MailingAddress'
  resources :billing_addresses, controller: 'addresses', type: 'BillingAddress'

  resources :users
  resources :home

  namespace :admin do
    resources :items, :categories, :orders, :order_items
    resources :stores, except: :patch
    patch 'stores/:id', to: 'stores#authorize_store', as: "authorize_store"
    get 'dashboard', to: 'dashboard#show'
  end

  get 'cart',        to: 'carts#show',  as: 'cart'

  get 'confirmation', to: 'confirmations#show'

  get 'code', to: 'home#code'

  get 'complete_delivery_order', to: 'orders#create'

  get 'checkout',         to: 'checkouts#show'
  get 'complete_order',   to: 'checkouts#complete_order'

  post 'add_item',         to: 'carts#add_item',       as: 'add_item'
  get 'remove_item',      to: 'carts#remove_item',    as: 'remove_item'
  put 'update_quantity',  to: 'carts#update_quantity',as: 'update_quantity'

  namespace :seller do
    resources :items, :orders
    get  'stores',                    to: 'seller#index',           as: 'dashboard'
    get  'store/:id/edit',            to: 'seller#edit',            as: 'store_edit'
    get  'store/:id',                 to: 'seller#show',            as: 'store_show'
    patch 'store/:id',                to: 'seller#update',          as: 'store_update'
    patch 'store/add_manager/:id',    to: 'seller#add_manager',     as: 'store_add_manager'
    patch 'store/remove_manager/:id', to: 'seller#remove_manager',  as: 'store_remove_manager'
  end

  get 'stores', to: 'store_dashboard#index', as: 'store_dashboard'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get  'request_store', to: 'stores#new', as: 'request_store'
  post 'send_store_request',  to: 'stores#create'

  get 'about',      to: 'about#show'

  get "contact_us", to: 'contact_us#new'
  resources "contact_us", only: [:create]

  get ':store_name', to: 'stores#show', as: 'stores'
end

app/models/cart.rb
class Cart
  def initialize(session)
    @session ||= session
  end

  def add_item(item_id, options)
    if !items[item_id].nil?
      items[item_id] = [((items[item_id][0] || 0) + 1), (items[item_id][1] || options)]
    else
      items[item_id] = [((items[item_id] || 0) + 1), (items[item_id] || options)]
    end
  end

  def remove_item(item_id)
    items.delete(item_id)
  end

  def update_quantity(item_id, quantity)
    items[item_id][0] = quantity
  end

  def item(item_id)
    Item.find(item_id)
  end

  def line_item_price(item_id, quantity)
    item(item_id).price * quantity[0].to_i
  end

  def items
    @session[:cart_items] ||= {}
  end

  def empty?
    items.empty?
  end

  def self.subtotal(session)
    prices = session[:cart_items].map do |item_id, quantity|
      Item.find(item_id).price * quantity[0].to_i
    end
    prices.reduce(:+)
  end

  def self.tax(session)
    subtotal(session) * ".05".to_f
  end

  def self.total(session)
    subtotal(session) + tax(session)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    if cart.items.any?
      @subtotal = Cart.subtotal(session)
      @tax = Cart.tax(session)
      @total = Cart.total(session)
    end
  end

  def add_item
    cart.add_item(params[:item_id], params[:options])
    item = Item.find(params[:item_id])
    store = Store.find(item.store_id)
    redirect_to cart_path
  end

  def remove_item
    cart.remove_item(params[:item_id])
    redirect_to cart_path
  end

  def update_quantity
    cart.update_quantity(params[:item_id], params[:quantity].to_i)
    redirect_to cart_path
  end
end

app/views/carts/show.html.erb
<div id="cart-container">
<h1 id="checkout-cart-header">The Dopest Cart</h1>
<%= flash[:notice] %>
  <% if cart.items.any? %>
    <table class="tg" id="cart_table">
      <tr>
        <th> Item Name </th>
        <th> Quantity </th>
        <th> Options </th>
        <th> Price </th>
        <th> Delete </th>
        <th> Totals </th>
      </tr>

    <% cart.items.each_pair do |id, options| %>
      <tr>
        <td> <%= cart.item(id).name %> </td>
        <td>
            <%= form_tag update_quantity_path, :method => :put do  %>
              <%= hidden_field_tag "item_id", id %>
              <%= number_field_tag "quantity", options[0], :min => 1, :max => 100 %>
              <%= submit_tag "update" %>
            <% end %> </td>
        <td> <% options[1].each do |k, v| %>
                <%= k.singularize.capitalize %> - <%= v %>
             <% end %> </td>
        <td> <%= number_to_currency(cart.item(id).price) %> </td>
        <td> <%= link_to "Remove", remove_item_path(item_id: id) %> </td>
        <td> <%= number_to_currency(cart.line_item_price(id, options)) %> </td>

      </tr>
    <% end %>
      <tr>
        <td colspan="5">Sub-total: </td>
        <td><%= number_to_currency(@subtotal) %></td>
      </tr>
      <tr>
        <td colspan="5">Tax: </td>
        <td><%= number_to_currency(@tax) %></td>
      </tr>
      <tr>
        <td colspan="5">Total: </td>
        <td><%= number_to_currency(@total) %></td>
      </tr>
    </table>
  <% end %>
  </br>

  <div>
    <div class="pickup-delivery-button">
          <%= link_to "Complete Order", new_order_path, class: "btn btn-primary btn-lg", id: "delivery_btn" %>
    </div>
  </div>
  </br>
  <%= form_tag root_path, method: :get do %>
    <%= button_tag(:class => "btn btn-success btn-sm", :id => "continue_shopping_btn") do %>
       continue shopping <span class="glyphicon glyphicon-shopping-cart" ></span>
    <% end %>
  <% end %>
</div>